### ISSUE TITLE
Possible infinite loop with hostname canonicalization

### ISSUE THREAD

**Issue by roblourens** [cyjake/ssh-config#81]
Originally reported in https://github.com/microsoft/vscode-remote-release/issues/9801

To summarize, this user has `CanonicalizeHostname yes`, and when we try to resolve the config, ssh-config seems to be stuck in an infinite loop of calling nslookup. I haven't been able to reproduce the issue but I see that it could maybe happen. When using a different DNS server, nslookup might return a different result from what you are looking for.

This is
https://github.com/cyjake/ssh-config/blob/2a134ab970b214730b67df9906e3ce26c4b03dbd/src/ssh-config.ts#L229-L230

Even though I didn't repro it, maybe you see the issue- I can try to debug more or get more information if this report isn't enough.o

**Comment by cyjake** [comment]
The loop itself doesn't look like can be infinite. Can you extract the problematic ssh config? I'll try to reproduce the issue as well.

**Comment by grawity** [comment]
The minimal example is at: https://github.com/microsoft/vscode-remote-release/issues/9801#issue-2254311009

The original full config is at: https://gist.github.com/grawity/2c989214f6b81130a31fe42912ca0c5c

I don't know if it's that particular loop – although it definitely has the wrong expectations as to the output of nslookup (which is not guaranteed to say `server can't find` – it actually says `** <hostname> can't find` on Windows), and it's the only mention of nslookup within the extension that I had found.

**Comment by cyjake** [comment]
will vscode try to compute the ssh-config again if the returned Host is not available? The loops within SSHConfig#compute would not stuck no matter the nslookup result.

I should still change the way to determine the result though. Can you change the code from

```js
... {stdout:s}=(0,i.spawnSync)("nslookup",[o]);if(!/server can't find/.test((s.toString())) ...
```

to

```js
... {status:s}=(0,i.spawnSync)("nslookup",[o]);if(status===0) ...
```

and see if the problem persists or not?

**Comment by cyjake** [comment]
@roblourens @grawity Does the problem persist with the main branch ssh-config? I'll release a patch version today if everything is ok

**Comment by grawity** [comment]
Thanks for reminding; I finally got around to trying the manual change you suggested last week https://github.com/cyjake/ssh-config/issues/81#issuecomment-2069093523 (since I probably can't rebuild the extension myself), but it does not seem to have any effect on the overall problem. I still see vscode spawning the same `nslookup.exe *.example.net` (always trying to do a `*.foo` lookup for whatever `foo` was the 1st item in my CanonicalDomains).

**Comment by cyjake** [comment]
what was the exact CanonicalDomains? I wonder where does that `*.` come from. Anyway, I still don't think the endless loop is caused by the library itself, further investigation on the referencing issue is needed.

**Comment by grawity** [comment]
I linked the exact ssh/config earlier but it happens regardless of the specific CanonicalDomains value, as long as it has at least two domains, e.g. I also tried with `example.net example.com` and got a `nslookup *.example.net` running.

**Comment by roblourens** [comment]
I looked at my code again to be sure that we wouldn't be calling into ssh-config in a loop. I'm pretty sure that's not the case.

@grawity if you are up for making more manual changes, if you wanted to hack any `console.log` into this code, then those should show up in the Extension Host output channel in vscode.

**Comment by cyjake** [comment]
@roblourens if no `Host` were found, will the extension try to parse the config again?

**Comment by roblourens** [comment]
No

**Comment by grawity** [comment]
I poked around some more. The loop is definitely inside compute(), where doPass() calls itself again, with exactly the same parameters.

The change from stdout to status probably didn't have the right effect, 1) because nslookup on Windows never exits with any other status than 0, though (and 0 typically means success, >0 is failure), and 2) because the "can't find" message actually goes to `stderr`, not stdout, so even if the regex was correct it would've never matched anything...

Either way, though, if I comment out the whole if(status) recursive call, then it no longer gets stuck completely.

The fact that it makes `*.domain` queries is somewhat suspicious though. Shouldn't that have been `host.domain`? In my case, I see that `compute("ember")` was initially called, so I would have expected it to try `ember.domain1`, `ember.domain2`, etc. – but since it found the CanonicalDomains setting underneath `Host *`, that seems to overwrite the hostname...

**Comment by cyjake** [comment]
@grawity sorry about overlooking the `*.domain` issue earlier, it clearly is a bug in the library. I've added a test case and a fix to work around said scenario, also included a new check regarding windows nslookup stderr. Could you help taking a look about the new pr, try to run the tests on Windows machine?

**Comment by cyjake** [comment]
@roblourens the dead loop is indeed caused by the recursive doPass() calls, thanks for reporting the issue and the quick feedbacks!

**Comment by cyjake** [comment]
v4.4.4 released

**Comment by roblourens** [comment]
Thanks @cyjake and thanks @grawity for the investigation! I've adopted this in the extension (but it won't be published for a few days as releases are paused for the Build conference)
